### ISSUE TITLE
请问在SMPL & Rendering中，detectron2和4D-Humans两个项目都放在champ目录下吗？

### ISSUE THREAD

**Issue by 1664062748** [fudan-generative-vision/champ#149]
我在运行这一步时出现了问题
![屏幕截图 2024-07-28 161602](https://github.com/user-attachments/assets/6c444327-965f-4e3b-97c9-868ca5132f0e)
![屏幕截图 2024-07-28 161652](https://github.com/user-attachments/assets/106c754d-cd8c-497c-8850-a028f394e2ff)

**Comment by 1664062748** [comment]
![屏幕截图 2024-07-29 205727](https://github.com/user-attachments/assets/7de8e887-d81a-4047-bde3-97ea44cdd861)
我的detectron2和4D-Humans这两个项目放在了champ目录下，运行报错结果如上

**Comment by fransonwu** [comment]
我是放在4D-Humans下。   4D-Humans不在champ下，和champ平级。
然后执行命令的时候，到champ下执行（还是在4D-Humans虚拟环境里）。
我试了好久，文档不清楚。 而且代码还有错。你马上会遇到报错。

**Comment by HiouKaoru** [comment]
请问你们在python -m scripts.pretrained_models.download --hmr2这一步有没有遇到问题，我执行这步的时候会报错
Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 67, in EGL
    return ctypesloader.loadLibrary(
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('EGL: cannot open shared object file: No such file or directory', 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/jovyan/champ/scripts/pretrained_models/__init__.py", line 5, in <module>
    from hmr2.models import CACHE_DIR_4DHUMANS
  File "/home/jovyan/champ/././4D-Humans/hmr2/models/__init__.py", line 2, in <module>
    from .hmr2 import HMR2
  File "/home/jovyan/champ/././4D-Humans/hmr2/models/hmr2.py", line 7, in <module>
    from ..utils import SkeletonRenderer, MeshRenderer
  File "/home/jovyan/champ/././4D-Humans/hmr2/utils/__init__.py", line 4, in <module>
    from .renderer import Renderer
  File "/home/jovyan/champ/././4D-Humans/hmr2/utils/renderer.py", line 6, in <module>
    import pyrender
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/pyrender/light.py", line 10, in <module>
    from OpenGL.GL import *
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 'EGL: cannot open shared object file: No such file or directory', 'EGL', None)

我的环境是远程linux ubuntu2204，非root用户

**Comment by chhandsomed** [comment]
4D-Humans  should  put into /root/.cache/    and  detectron2 should choose detectron2/detectron2  into champ

**Comment by chenfei8888** [comment]
> 请问你们在python -m scripts.pretrained_models.download --hmr2这一步有没有遇到问题，我执行这步的时候会报错 Traceback (most recent call last): File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 67, in EGL return ctypesloader.loadLibrary( File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary return dllType( name, mode ) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/ctypes/**init**.py", line 374, in **init** self._handle = _dlopen(self._name, mode) OSError: ('EGL: cannot open shared object file: No such file or directory', 'EGL', None)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/runpy.py", line 187, in _run_module_as_main mod_name, mod_spec, code = _get_module_details(mod_name, _Error) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/runpy.py", line 110, in _get_module_details **import**(pkg_name) File "/home/jovyan/champ/scripts/pretrained_models/**init**.py", line 5, in from hmr2.models import CACHE_DIR_4DHUMANS File "/home/jovyan/champ/././4D-Humans/hmr2/models/**init**.py", line 2, in from .hmr2 import HMR2 File "/home/jovyan/champ/././4D-Humans/hmr2/models/hmr2.py", line 7, in from ..utils import SkeletonRenderer, MeshRenderer File "/home/jovyan/champ/././4D-Humans/hmr2/utils/**init**.py", line 4, in from .renderer import Renderer File "/home/jovyan/champ/././4D-Humans/hmr2/utils/renderer.py", line 6, in import pyrender File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/pyrender/**init**.py", line 3, in from .light import Light, PointLight, DirectionalLight, SpotLight File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/pyrender/light.py", line 10, in from OpenGL.GL import * File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/GL/**init**.py", line 3, in from OpenGL import error as _error File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/error.py", line 12, in from OpenGL import platform, _configflags File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/**init**.py", line 35, in _load() File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/**init**.py", line 32, in _load plugin.install(globals()) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 92, in install namespace[ name ] = getattr(self,name,None) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 14, in **get** value = self.fget( obj ) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext return self.EGL.eglGetCurrentContext File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/baseplatform.py", line 14, in **get** value = self.fget( obj ) File "/home/jovyan/.conda/envs/4D-humans/lib/python3.10/site-packages/OpenGL/platform/egl.py", line 73, in EGL raise ImportError("Unable to load EGL library", *err.args) ImportError: ('Unable to load EGL library', 'EGL: cannot open shared object file: No such file or directory', 'EGL', None)
> 
> 我的环境是远程linux ubuntu2204，非root用户

请问您解决了吗？

**Comment by YxY-HK** [comment]
> 请问您解决了吗？

因为是公司的服务器，所以申请了root权限后，安装apt-get install mesa-utils libegl1-mesa libegl1-mesa-dev libgles2-mesa-dev就解决了
