### ISSUE TITLE
where is model_config.yaml?

### ISSUE THREAD

**Issue by puppy9207** [fudan-generative-vision/champ#50]
Traceback (most recent call last):
  File "/workspace/champ/4D-Humans/inference_smpl.py", line 74, in <module>
    model, model_cfg = load_hmr2(DEFAULT_CHECKPOINT)
  File "/workspace/champ/4D-Humans/hmr2/models/__init__.py", line 72, in load_hmr2
    model_cfg = get_config(model_cfg, update_cachedir=True)
  File "/workspace/champ/4D-Humans/hmr2/configs/__init__.py", line 103, in get_config
    cfg.merge_from_file(config_file)
  File "/opt/conda/lib/python3.10/site-packages/yacs/config.py", line 211, in merge_from_file
    with open(cfg_filename, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/4DHumans/logs/train/multiruns/hmr2/0/model_config.yaml'

No matter how hard I look, I can't find the relevant yaml file. Is there anything I missed?

**Comment by LEES0196** [comment]
Try running the demo code in the 4D-humans project page.
It will probabily set up properly after downloading several checkpoints and configurations.

**Comment by puppy9207** [comment]
It works me!
